const COLORS = {
  BUTTON_COLOR: '#547DBF',
  BORDER_COLOR: '#DFE1E7',
  DARK_RED_COLOR: '#CF1C3B',
  LIGHT_RED_COLOR: '#FFEBF1',
  SECONDARY_COLOR: '#F7F8FA',
  WHITE: '#FFFFFF',
  INCOME_COLOR: '#30A953',
};

export default COLORS;
